### ISSUE TITLE
AMAZING

### ISSUE THREAD

**Issue by PDMADETHAT** [strain08/Pro-Tools-Fullscreen-App#4]
i love you 
i love you 
i love you 
i love you 
i love you 
i love you 
i love you 

but please make the transport borderless aswell

**Comment by strain08** [comment]
i'm glad you like it
i'm glad you like it
i'm glad you like it
i'm glad you like it
i'm glad you like it

This little guy?
![image](https://github.com/user-attachments/assets/d822cd41-05cc-4d9a-926e-00a2adcefb8c)

In principle it can be done, however by removing the border you also remove the ability to move the window around. 
Quite cumbersome.

Meanwhile I came across this: https://github.com/MicaForEveryone

I opened a discussion on this matter here:
https://github.com/MicaForEveryone/MicaForEveryone/discussions/484

**Comment by PDMADETHAT** [comment]
i came across an issue in PT12 when your settings are enabled i cannot move any faders

**Comment by strain08** [comment]
I can't reproduce this on PT 2024.6

**Comment by PDMADETHAT** [comment]
i am on pro tools 12.

**Comment by PDMADETHAT** [comment]
can it b fixedf?

**Comment by strain08** [comment]
I don't think so.  It may be the same reason why moving events/fades with menu visible is glitching, an internal offset that is calculated based on controls posision relative to the window edges My code doesn't do much except changing the window style.  I'm sorry it does not work for you.

**Comment by PDMADETHAT** [comment]
what version of pro tools are you on?

**Comment by strain08** [comment]
2024.6

**Comment by PDMADETHAT** [comment]
what files can i edit to remove the border myself locally

**Comment by strain08** [comment]
I have no clue what files you are talking about. You can locally modify the source code as you see fit.

**Comment by bzeiss** [comment]
This thingy is supercool! Thank you for making it!
